#baseurl = "/docs"
relativeurls = true
languageCode = "en-us"
title = "Material Kit by Creative Tim"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
#enableGitInfo = true
publishDir = "docs"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    pre = "<i class='fa fa-home'></i>"
    name = "Landing"
    url = "/landing"
    weight = 2
[[menu.main]]
    pre = "<i class='fa fa-user'></i>"
    name = "Profile"
    url = "/profile"
    weight = 3
[[menu.main]]
    name = "Signup"
    url = "/signup"
    weight = 4
[[menu.main]]
    pre = "<i class='material-icons'>apps</i>"
    name = "Components"
    identifier = "dropdown"
    url = "#"
    weight = 1
[[menu.main]]
    parent = "dropdown"
    pre = "<i class='material-icons'>layers</i>"
    name = "All Components"
    url = "#"
[[menu.main]]
    parent = "dropdown"
    pre = "<i class='material-icons'>content_paste</i>"
    name = "Documentation"
    url = "#"


[[menu.footer]]
    identifier = "twitter"
    pre = "<i class='fa fa-twitter'></i>"
    url = "https://twitter.com/CreativeTim"
    weight = 1
[[menu.footer]]
    identifier = "github"
    pre = "<i class='fa fa-github'></i>"
    url = "https://github.com/CreativeTim"
    weight = 2
[[menu.footer]]
    identifier = "copyright"
    name = "MIT"
    pre = "<i class='fa fa-balance-scale'></i>"
    url = "https://spdx.org/licenses/MIT"
    weight = 3    


[params]
#    background = "https://climate.nasa.gov/system/internal_resources/details/original/417_1263_banner-science-1600x500.jpg"
    name =  ""
    twitter =  ""
    github =  ""
    email =  ""
#    custom_css = []
#    repo = ""
#    branch = "source"
#    math = true

    date_format = "Mon, Jan 2, 2006"
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.10.0"
    highlightCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"


    

